# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Machine Debian11
  config.vm.define "debian11" do |debian11|
    debian11.vm.hostname = "Debian11"
    debian11.vm.network "private_network", ip: "192.168.60.10"

    # Config vm
    debian11.vm.provision "shell", inline: <<-SHELL
     # echo 'deb http://deb.debian.org/debian/ bullseye-backports main' >> /etc/apt/sources.list     
      apt-get update
      apt-get install -y openssh-server

      # Add user
      adduser --gecos "" root-max
      echo "root-max:max" | chpasswd
      usermod -aG sudo root-max

      # Enable password authentication for SSH
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

      # Ajouter le clavier en azerty
      localectl set-keymap fr
      # Changer la langue du système en français
      localectl set-locale LANG=fr_FR.UTF-8
      
      systemctl restart ssh
      systemctl enable ssh
      systemctl start ssh
      reboot
    SHELL
  end
  config.vm.post_up_message = <<-MESSAGE
   debian11
   Utilisateur : root-max - Mot de passe : max
   Utilisateur : vagrant - Mot de passe : aucun
 
   SSH
   vagrant ssh debian11
   ssh root-max@127.0.0.1 -p 2222
   ssh root-max@192.168.60.10
  MESSAGE
end
